// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYb6hAk6x3n4VLWQXaRQAiLTtfGTpsZg',
    appId: '1:670206504584:web:91bcb6e6518e6f22b9793d',
    messagingSenderId: '670206504584',
    projectId: 'fir-authentication-6a3f7',
    authDomain: 'fir-authentication-6a3f7.firebaseapp.com',
    storageBucket: 'fir-authentication-6a3f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzNavoM0LD6_r_tEkpJ8tSgAe_tSNIbE',
    appId: '1:670206504584:android:069f50e07cc06cfbb9793d',
    messagingSenderId: '670206504584',
    projectId: 'fir-authentication-6a3f7',
    storageBucket: 'fir-authentication-6a3f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh9-PuS3hJZT71AI-HZNBDGv091KgtSD8',
    appId: '1:670206504584:ios:a57e5b02d8848c90b9793d',
    messagingSenderId: '670206504584',
    projectId: 'fir-authentication-6a3f7',
    storageBucket: 'fir-authentication-6a3f7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh9-PuS3hJZT71AI-HZNBDGv091KgtSD8',
    appId: '1:670206504584:ios:a57e5b02d8848c90b9793d',
    messagingSenderId: '670206504584',
    projectId: 'fir-authentication-6a3f7',
    storageBucket: 'fir-authentication-6a3f7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIYb6hAk6x3n4VLWQXaRQAiLTtfGTpsZg',
    appId: '1:670206504584:web:ca00f3d322d16e49b9793d',
    messagingSenderId: '670206504584',
    projectId: 'fir-authentication-6a3f7',
    authDomain: 'fir-authentication-6a3f7.firebaseapp.com',
    storageBucket: 'fir-authentication-6a3f7.firebasestorage.app',
  );
}
